version: '3.9'
x-pdi-common:
  &pdi-common
  build:
    context: ./setup-pentaho
    dockerfile: Dockerfile
    args:
      PENTAHO_UID: ${PENTAHO_UID}
      PENTAHO_GID: ${PENTAHO_GID}
  image: pdi
  environment:
    &pdi-common-env
    HOST_ENV: ${HOST_ENV:-localhost}
    PENTAHO_DI_JAVA_OPTIONS: ${PENTAHO_DI_JAVA_OPTIONS}
    CARTE_USER: ${CARTE_USER}
    CARTE_PASSWORD: ${CARTE_PASSWORD}
  volumes:
    # - /var/run/docker.sock:/var/run/docker.sock
    - ./source-code/ktrs:/home/pentaho/repositories
    - ./setup-pentaho/logs:/opt/data-integration/logs
    - ./setup-pentaho/repositories.xml:/opt/data-integration/.kettle/repositories.xml
    - ./setup-pentaho/kettle-properties/${HOST_ENV:-localhost}-kettle.properties:/opt/data-integration/.kettle/kettle.properties
    - ./setup-pentaho/simple-jndi:/opt/data-integration/simple-jndi
  deploy:
    restart_policy:
      condition: on-failure
      max_attempts: 3

services:
# Pentaho
  pdi-master:
    << : *pdi-common
    container_name: pdi-master
    environment:
      <<: *pdi-common-env
    ports:
      - ${CARTE_HOST_PORT:-8181}:8181

  # pdi-child:
  #   << : *pdi-common
  #   container_name: pdi-child
  #   ports:
  #     - 8182
  #   depends_on:
  #     - pdi-master
  #   environment:
  #     <<: *pdi-common-env
  #     CARTE_PORT: 8182
  #     CARTE_IS_MASTER: 'N'
  #     CARTE_INCLUDE_MASTERS: 'Y'
  #     CARTE_MASTER_HOSTNAME: 'pdi-master'
  #     CARTE_MASTER_PORT: ${CARTE_HOST_PORT:-8181}

volumes:
  postgres-db-volume: