version: '3.9'

services:
  apache-hop:
    container_name: hop_container
    image: apache/hop:latest
    ports:
      - 8081:8081
    volumes:
#      - ./var:/home/hop
      - ./files:/files  #  You can use it for example to mount a folder that contains the hop and project config as well as the workflows and pipelines.
    environment:
      HOP_SERVER_USER: cluster
      HOP_SERVER_PASS: cluster
      HOP_SERVER_PORT: 8081
      HOP_SERVER_HOSTNAME: 0.0.0.0 #Placeholder for testing
      HOP_PROJECT_NAME: hop_container
      HOP_FILE_PATH: ${PROJECT_HOME}/write-to-log.hwf
      HOP_PROJECT_DIRECTORY: /files/
      HOP_ENVIRONMENT_NAME: test
      HOP_ENVIRONMENT_CONFIG_FILE_NAME_PATHS: test
      HOP_RUN_CONFIG: local

