version: '3.9'

services:
  hop-server:
    container_name: hop-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: apache/hop:latest
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    command: ["/opt/hop/run.sh"]
    restart: unless-stopped
    ports:
      - 8181:8181 #Porta 8182 do host mapeada para a porta 8081 do contêiner
      - 8079:8079
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      HOP_PROJECT_NAME: ${HOP_PROJECT_NAME:-engdados}
      HOP_PROJECT_FOLDER: ${HOP_PROJECT_FOLDER:-/hop/projects}
      HOP_RUN_CONFIG: ${HOP_RUN_CONFIG:-local} #execução local no container
      HOP_SERVER_USER: ${HOP_SERVER_USER:-admin}
      HOP_SERVER_PASS: ${HOP_SERVER_PASS:-admin}
      HOP_SERVER_PORT: ${HOP_SERVER_PORT:-8181}
      HOP_SERVER_SHUTDOWNPORT: ${HOP_SERVER_SHUTDOWNPORT:-8079}
      HOP_SERVER_HOSTNAME: ${HOP_SERVER_HOSTNAME:-0.0.0.0}
      HOP_ENVIRONMENT_NAME: ${HOP_ENVIRONMENT_NAME:-Development}
      TZ: America/Recife
#      HOP_CONFIG_FOLDER: /hop/projects/config
#      HOP_LOG_LEVEL: Basic
#      HOP_ENVIRONMENT_NAME: dev
#      HOP_ENVIRONMENT_CONFIG_FILE_NAME_PATHS: /files/config/web-samples-test.json --name hop-web-test-container
#      HOP_FILE_PATH: ${PROJECT_HOME}/write-to-log.hwf
#    HOP_PROJECT_CONFIG_FILE_NAME: project-config.json
    volumes:
      - ./data/server/projects:/hop/projects
    networks:
      - hop-network

  hop-web:
    container_name: hop-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: apache/hop-web:latest
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    command: ["/tmp/run-web.sh"]
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      HOP_PROJECT_NAME: ${HOP_PROJECT_NAME:-engdados}
      HOP_PROJECT_FOLDER: ${HOP_PROJECT_FOLDER:-/hop/projects}
      HOP_RUN_CONFIG: ${HOP_RUN_CONFIG:-local} #execução local no container
      HOP_ENVIRONMENT_NAME: ${HOP_ENVIRONMENT_NAME:-Development}
      TZ: America/Recife
#      HOP_CONFIG_FOLDER: /hop/projects/config
#      HOP_LOG_LEVEL: Basic
#      HOP_ENVIRONMENT_NAME: dev
    volumes:
      - ./data/web_ui/projects:/hop/projects
    networks:
      - hop-network
    depends_on:
      - hop-server

networks:
  hop-network:
    driver: bridge